name: grid2op-environment
channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - numpy
  - keras
  - pip
  - pip:
    - grid2op
    - numpy
    - numba
    - seaborn
    - plotly
    - imageio
